version: "3"

services:
  node:
    image: node:16
    container_name: password_validate
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080

networks:
  default:
    name: password_validate

